### ISSUE TITLE
User search feature should be using login name as its more familiar to non-managers

### ISSUE THREAD

**Issue by djay** [collective/collective.pfg.signup#14]
Currently all the code for managing users is showing and allowing search for userid only. Sometimes userid and login are different.
https://github.com/collective/collective.pfg.signup/blob/dde958b3c358cfd9b2dd73f7f8409286e5dea441/collective/pfg/signup/templates/user_search_view.pt#L105

There is a related issue #15 where userid is picked by the user using the adapter where it should be only loginname and plone should determine the userid based on the policy.

**Comment by JeffersonBledsoe** [comment]
Solved by collective/collective.pfg.signup#16
